---
- name: Get deployed application URL
  hosts: testservers
  tasks:
    - name: Generate application URL
      shell: echo "application_url={{ hostvars[item]['ansible_default_ipv4']['address'] }}:8081" >> application_url.txt
      loop: "{{ ansible_play_batch }}"
      run_once: true
      when: "'testservers' in group_names"
