---
- name: Configure Docker on EC2 Instances
  hosts: testservers
  become: true
  connection: ssh
  tasks:
    - name: Updating apt
      command: sudo apt-get update

    - name: Install Docker
      command: sudo apt-get install -y docker.io

    - name: Start Docker Service
      command: sudo systemctl start docker

    - name: Deploy Docker Container
      command: docker run -itd -p 8085:8081 sejalmm06/finance-me:latest

- name: Get deployed application URL
  hosts: testservers
  tasks:
    - name: Generate application URL
      shell: echo "application_url={{ hostvars[item]['ansible_default_ipv4']['address'] }}:8081" >> application_url.txt
      loop: "{{ ansible_play_batch }}"
      run_once: true
      when: "'testservers' in group_names"
